### ISSUE TITLE
Dashboard Overview Page

### ISSUE THREAD

**Issue by loljoho** [GPQuery/gpquery-dashboard#5]
Create the Dashboard Main Page using the Ergast Data Service created in #4 
- [ ] Add custom actions to the `Ergast` data service if necessary, #8 
- [ ] Implement `Ergast` data service in routing `resolve`
- [ ] Determine widgets to include, #7
- [ ] Create widget directives, #7
- [ ] Implement widgets, #7
